### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/rfcs#1]
Place holder issue for features and goals we may wish to accomplish. Comment below with suggestions with the list.

### Feature list

- [ ] Basic HAL for each chip, covering common peripherals; gpio, i2c, spi etc.
- [ ] Support for xtensa peripherals (system peripherals)
- [ ] Functional wifi/bluetooth
- [ ] [RTFM](https://rtfm.rs/) integration, (will require interrupt info see https://github.com/esp-rs/esp32/issues/12 )

**Comment by davidkern** [comment]
When I was first setting up a dev environment to help on the project, I found it a little difficult because information on what to do is split across a number of repos (e.g. rustc fork, llvm fork, a few gists).  It is probably the case for others as well, and there will be other documentation that'll be needed as all the pieces evolve.

The question is then: what centralized location in esp-rs makes sense for evolving user documentation for Rust on ESP?

**Comment by MabezDev** [comment]
Yeah the documentation thus far is just a series of note I left for myself really. [This isn't the first time](https://github.com/MabezDev/xtensa-rust-quickstart/issues/6) its been brought up either so I need to sit down and colllate all the info.

As for where, I'm not to sure.

**Comment by davidkern** [comment]
I'm happy to pitch in on this as well.  Hopefully everyone changing something could also help keep docs updated - as there will be a lot of internals to track.

Unless someone has a better solution, may I suggest adding a 'docs' repo to the org with gh-pages setup?  We can all then just submit PRs to it to keep everything up-to-date.

**Comment by MabezDev** [comment]
That's a good idea, I've created [the docs](https://github.com/esp-rs/docs) repo. It might be easier to start off with just some mark down files as I expect the state of how we do things to be quite volatile this early in the project.

**Comment by arjanmels** [comment]
The flash support is done in: https://github.com/esp-rs/esp32-hal/pull/16

**Comment by MabezDev** [comment]
Pinging this thread as we are about to delete this repo, we're now tracking the project in a org project: https://github.com/orgs/esp-rs/projects/2
